module.exports = {
	SPOTIFY_CLIENT_ID: process.env.SPOTIFY_CLIENT_ID,
	SPOTIFY_CLIENT_SECRET: process.env.SPOTIFY_CLIENT_SECRET,
	SPOTIFY_REDIRECT_URI: SPOTIFY_REDIRECT_URI,
	GENIUS_ACCESS_TOKEN: process.env.GENIUS_ACCESS_TOKEN,
	GOOGLE_PROJECT_ID: process.env.GOOGLE_PROJECT_ID
}
